### ISSUE TITLE
Error occurred prerendering page "/campus-ambassador".

### ISSUE THREAD

**Issue by fal3n-4ngel** [CROSSROADS-2024/CR-24-updated#6]
RangeError: Maximum call stack size exceeded
    at m (C:\Users\Lenovo\Desktop\CR-24-updated\.next\server\app\campus-ambassador\page.js:2466:89406)
    at m (C:\Users\Lenovo\Desktop\CR-24-updated\.next\server\app\campus-ambassador\page.js:2466:90057)
    at m (C:\Users\Lenovo\Desktop\CR-24-updated\.next\server\app\campus-ambassador\page.js:2466:90057)
    at m (C:\Users\Lenovo\Desktop\CR-24-updated\.next\server\app\campus-ambassador\page.js:2466:90057)
    at m (C:\Users\Lenovo\Desktop\CR-24-updated\.next\server\app\campus-ambassador\page.js:2466:90057)
    at m (C:\Users\Lenovo\Desktop\CR-24-updated\.next\server\app\campus-ambassador\page.js:2466:90057)
    at m (C:\Users\Lenovo\Desktop\CR-24-updated\.next\server\app\campus-ambassador\page.js:2466:90057)
    at m (C:\Users\Lenovo\Desktop\CR-24-updated\.next\server\app\campus-ambassador\page.js:2466:90057)
    at m (C:\Users\Lenovo\Desktop\CR-24-updated\.next\server\app\campus-ambassador\page.js:2466:90057)
    at m (C:\Users\Lenovo\Desktop\CR-24-updated\.next\server\app\campus-ambassador\page.js:2466:90057)
Error occurred prerendering page "/campus-ambassador"

**Comment by DAREDEVILDD7** [comment]
Issue fixed
